# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashTags',
            new_name='HashTag',
        ),
    ]
