# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20160323_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
